version: '3.9'
services:
  app:
    build: .
    container_name: outfitforyou_fast_api
    ports:
      - "8035:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000